logging:
  level:
    org:
      springframework:
        beans: info
        context: info
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_db1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: on
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true